### ISSUE TITLE
de commandos in de README werken niet

### ISSUE THREAD

**Issue by raoulg** [megamaster4/dme_hu_maxpot#5]
`python main.py --callapi --num-processes` werkt niet:
Error: Option '--num-processes' requires an argument.

Maar dat toevoegen werkt ook niet:
```
python main.py --callapi --num-processes 4
Traceback (most recent call last):
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/main.py", line 77, in <module>
    main()
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: main() missing 1 required positional argument: 'dashboard'
```
Misschien moet ik eerst de data processen?
```
python main.py --process-parquet
Error: Option '--process-parquet' requires an argument.
```
Maar dat werkt ook niet. Ik moet waarschijnlijk de folder specificeren.

Maar er IS helemaal geen data/parquet folder, die had waarschijnlijk moeten zijn aangemaakt met de eerste callapi die niet werkt zoals beschreven....

**Comment by raoulg** [comment]
Ik dacht, ik zet even je dashboard optie op False, eens kijken of de data dan wel gepulled wordt. Maar dan krijg ik dit:
```
python main.py --callapi --num-processes 4
Traceback (most recent call last):
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/main.py", line 77, in <module>
    main()
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/main.py", line 30, in main
    db_engine = DBEngine(**Settings().model_dump())
                           ^^^^^^^^^^
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 71, in __init__
    super().__init__(
  File "/Users/rgrouls/code/DME-opdrachten/dme_hu_maxpot/.venv/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for Settings
DBNAME
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
DBUSER
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
DBPASS
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
DBPORT
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
```

Ik weet niet wat er precies fout gaat, maar er lijkt een heleboel niet te werken, ook al ziet je code er verder uitstekend uit...

**Comment by raoulg** [comment]
Ah, ik heb geen .env file, daar gaat het waarschijnlijk mis... De .env staat in je gitignore, ik vermoed dat je die eruit wilt halen, en mogelijk dat het dan wel werkt.

Je moet wel nog je dashboard parameter fixen, want die wordt nu niet gegeven in main.

**Comment by megamaster4** [comment]
Je was me iets te snel, ik ben nog bezig met de makefile waarbij hij een .env file aanmaakt en je zelf de environment params kunt aanpassen. Ik ga deze vandaag verwerken in de readme.

De dashboard parameter is een stukje refactoring die ik ben vergeten, nu kun je met make run zowel de docker container opstarten + streamlit runnen.

**Comment by megamaster4** [comment]
Readme aangepast naar gebruik van makefile
